// DOM interaction checks; jsdom is only a test dependency, not an app dependency.
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');const {execFileSync}=require('node:child_process');
const {Script}=require('node:vm');
const {JSDOM}=require(process.env.JSDOM_PATH||'jsdom');
const base=path.resolve(__dirname,'..');
const html=execFileSync(process.env.PHP_BINARY||'php',[path.join(__dirname,'purchase-wizard-fixture.php')],{encoding:'utf8'});
const dom=new JSDOM('<body>'+html+'</body>',{runScripts:'outside-only',url:'http://localhost/rice/public/purchase/new'});
const window=dom.window,document=window.document;
window.HTMLElement.prototype.scrollIntoView=function(){};
window.confirm=()=>true;
// Run classic scripts with shared globals, matching the app's deferred script tags.
new Script(fs.readFileSync(path.join(base,'public/assets/js/locale.js'),'utf8')).runInContext(dom.getInternalVMContext());
new Script(fs.readFileSync(path.join(base,'public/assets/js/purchase-wizard.js'),'utf8')).runInContext(dom.getInternalVMContext());
new Script(fs.readFileSync(path.join(base,'public/assets/js/app.js'),'utf8')).runInContext(dom.getInternalVMContext());
document.addEventListener('DOMContentLoaded',()=>{
    try {
        const form=document.querySelector('[data-purchase-wizard]');
        const panes=Array.from(form.querySelectorAll('.purchase-step'));
        const input=(element,value)=>{element.value=value;element.dispatchEvent(new window.Event('input',{bubbles:true}));};
        const choose=(select,value)=>{
            const container=select.nextElementSibling;
            container.querySelector('input').focus();
            document.getElementById(container.querySelector('input').getAttribute('aria-controls')).querySelector('[data-value="'+value+'"]').click();
        };
        const menuFor=select=>document.getElementById(select.nextElementSibling.querySelector('input').getAttribute('aria-controls'));
        const open=select=>{const control=select.nextElementSibling.querySelector('input');control.focus();control.click();return menuFor(select);};
        const rowField=(row,name)=>row.querySelector('[data-item-field="'+name+'"]');
        assert.equal(panes[0].hidden,false);assert.equal(panes[1].hidden,true);
        document.getElementById('purchase-next').click();assert.equal(panes[0].hidden,false,'Missing supplier/warehouse blocks progress');
        input(form.elements.warehouse_id,'1');
        const supplierInput=form.elements.supplier_id.nextElementSibling.querySelector('input'),supplierMenu=menuFor(form.elements.supplier_id);
        supplierInput.getBoundingClientRect=()=>({top:550,bottom:590,left:100,right:380,width:280,height:40});
        supplierMenu.getBoundingClientRect=()=>({height:60});
        open(form.elements.supplier_id);
        assert.equal(supplierMenu.parentElement,document.body,'Dropdown escapes form and table clipping');
        assert.equal(supplierMenu.style.top,'594px','Short supplier menu opens directly below the input');
        supplierInput.getBoundingClientRect=()=>({top:730,bottom:770,left:100,right:380,width:280,height:40});
        window.dispatchEvent(new window.Event('resize'));
        assert.equal(supplierMenu.style.top,'666px','Menu above input uses actual height and no large gap');
        choose(form.elements.supplier_id,'1');
        document.getElementById('purchase-next').click();assert.equal(panes[1].hidden,false);
        document.getElementById('purchase-next').click();assert.equal(panes[1].hidden,false,'Missing rice item blocks review');
        const first=document.querySelector('.purchase-item');choose(rowField(first,'rice_type_id'),'1');
        input(rowField(first,'quantity'),'2.125');input(rowField(first,'unit_price'),'10.25');
        form.querySelector('.add-item').click();assert.equal(document.querySelectorAll('.purchase-item').length,2);
        const second=document.querySelectorAll('.purchase-item')[1];
        assert.equal(open(rowField(second,'rice_type_id')).querySelector('[data-value="1"]'),null,'Already selected rice type is absent from another row');
        choose(rowField(second,'rice_type_id'),'2');
        assert.equal(form.querySelector('.add-item').disabled,true,'Adding rows stops when all rice types are selected');
        input(rowField(second,'quantity'),'3.333');input(rowField(second,'unit_price'),'20.75');
        rowField(first,'quantity').focus();
        rowField(first,'quantity').dispatchEvent(new window.KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true,cancelable:true}));
        assert.equal(document.activeElement,rowField(second,'quantity'),'Down moves to the same column in the next row');
        assert.equal(rowField(first,'quantity').value,'2.125','Grid navigation does not change numeric values');
        rowField(second,'quantity').dispatchEvent(new window.KeyboardEvent('keydown',{key:'Enter',shiftKey:true,bubbles:true,cancelable:true}));
        assert.equal(document.activeElement,rowField(first,'quantity'),'Shift+Enter moves to the previous row');
        assert.equal(document.getElementById('wizard-amount').textContent,'90.94 MMK');
        document.getElementById('purchase-next').click();assert.equal(panes[2].hidden,false);assert.equal(document.querySelectorAll('#purchase-review-items tr').length,2);
        assert.equal(form.querySelectorAll('.purchase-item')[1],second,'Wizard retains entered DOM rows');
        input(form.elements.amount_paid,'20.01');assert.equal(document.getElementById('wizard-credit').textContent,'70.93 MMK');
        input(form.elements.amount_paid,'91');
        const rejected=new window.Event('submit',{bubbles:true,cancelable:true});form.dispatchEvent(rejected);
        assert.equal(rejected.defaultPrevented,true);assert.equal(document.getElementById('purchase-save').disabled,false,'Invalid payment does not lock Save');
        document.getElementById('wizard-pay-full').click();assert.equal(form.elements.amount_paid.value,'90.94');
        document.getElementById('purchase-back').click();assert.equal(panes[1].hidden,false);
        window.confirm=()=>false;second.querySelector('.remove-item').click();assert.equal(document.querySelectorAll('.purchase-item').length,2);
        window.confirm=()=>true;second.querySelector('.remove-item').click();assert.equal(document.querySelectorAll('.purchase-item').length,1);
        assert.equal(menuFor(rowField(second,'rice_type_id')),null,'Removed rows dispose their floating menus');
        assert.notEqual(open(rowField(first,'rice_type_id')).querySelector('[data-value="2"]'),null,'Removing an item makes its rice type selectable again');
        rowField(first,'quantity').focus();
        rowField(first,'quantity').dispatchEvent(new window.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));
        const keyboardRow=document.querySelectorAll('.purchase-item')[1];
        assert.ok(keyboardRow,'Enter in the last row adds an available rice item');
        assert.equal(document.activeElement,rowField(keyboardRow,'quantity'),'New row keeps focus in the same column');
        keyboardRow.querySelector('.remove-item').click();
        choose(rowField(first,'rice_type_id'),'2');
        form.querySelector('.add-item').click();
        const replacement=document.querySelectorAll('.purchase-item')[1];
        const replacementMenu=open(rowField(replacement,'rice_type_id'));
        assert.notEqual(replacementMenu.querySelector('[data-value="1"]'),null,'Changing a selection releases the previous rice type');
        assert.equal(replacementMenu.querySelector('[data-value="2"]'),null,'Current selection stays excluded from other rows');
        replacement.querySelector('.remove-item').click();
        assert.equal(first.querySelector('.remove-item').disabled,true);
        input(rowField(first,'quantity'),'100000000.001');input(rowField(first,'unit_price'),'100000000.01');
        assert.equal(document.getElementById('wizard-amount').textContent,'10,000,000,001,100,000.00 MMK','Large amounts retain exact cents');
        document.getElementById('purchase-next').click();document.getElementById('wizard-pay-full').click();
        const accepted=new window.Event('submit',{bubbles:true,cancelable:true});form.dispatchEvent(accepted);
        assert.equal(accepted.defaultPrevented,false);assert.equal(document.getElementById('purchase-save').disabled,true);
        console.log('PASS: Wizard steps, searchable item selection, dynamic rows, review, exact totals, payments, back navigation and submission validation');
    } catch(error){console.error(error);process.exitCode=1;}finally{window.close();}
},{once:true});
