<div class="metrics">
<div class="metric"><span><?= e(t('Total rice in stock')) ?></span><strong><?= e(num($stats['stock'])) ?> <small><?= e(t('တင်း')) ?></small></strong><small><?= e(t('Across all warehouses')) ?></small><i aria-hidden="true">▦</i></div>
<?php if(isset($stats['purchases'])): ?><div class="metric"><span><?= e(t('Purchases this month')) ?></span><strong><?= e(money($stats['purchases'])) ?> <small><?= e(t('MMK')) ?></small></strong><small><?= e(locale_date('F Y')) ?></small><i aria-hidden="true">▤</i></div><?php endif; ?>
<div class="metric"><span><?= e(t('Used in production')) ?></span><strong><?= e(num($stats['production'])) ?> <small><?= e(t('တင်း')) ?></small></strong><small><?= e(t('This month')) ?></small><i aria-hidden="true">⚙</i></div>
<div class="metric"><span><?= e(t('Warehouses')) ?></span><strong><?= e($stats['warehouses']) ?></strong><small><?= e(t('Storage locations')) ?></small><i aria-hidden="true">⌂</i></div>
</div>
<?php if(!$balances): ?><div class="flash warning"><?= e(t('Start by adding your warehouses, rice types and suppliers.')) ?> <?php if(can('settings.manage')): ?><a href="<?= e(url('settings')) ?>"><?= e(t('Open business settings →')) ?></a><?php endif; ?></div><?php endif; ?>
<div class="dashboard-grid"><section class="panel"><div class="panel-heading"><div><div class="eyebrow"><?= e(t('PURCHASE SPENDING')) ?></div><h2><?= e(t('{year} at a glance',['year'=>date('Y')])) ?></h2></div><?php if(can('reports.view')): ?><a href="<?= e(url('reports')) ?>"><?= e(t('View reports →')) ?></a><?php endif; ?></div>
<?php if($chart !== null): ?><div class="chart-container"><canvas id="purchase-chart" aria-label="<?= e(t('Monthly purchase amount in MMK')) ?>" role="img"></canvas></div><script type="application/json" id="chart-data"><?= json_encode($chart,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script><script src="<?= e(asset('vendor/chart.umd.min.js')) ?>" defer></script><?php if(!array_sum(array_column($chart,'amount'))): ?><p class="muted chart-caption"><?= e(t('Your purchase chart will fill in as you record purchases.')) ?></p><?php endif; ?><?php else: ?><div class="empty"><?= e(t('Purchase reports are available to staff with report access.')) ?></div><?php endif; ?>
</section><section class="panel"><div class="panel-heading"><div><div class="eyebrow"><?= e(t('STORAGE LOCATIONS')) ?></div><h2><?= e(t('Warehouse balances')) ?></h2></div><a href="<?= e(url('inventory')) ?>"><?= e(t('View all →')) ?></a></div>
<?php foreach($balances as $b): ?><div class="warehouse-row"><span class="warehouse-icon" aria-hidden="true">⌂</span><div><strong><?= e($b['name']) ?></strong><small><?= e($b['location']?:t('Warehouse')) ?></small></div><strong class="number"><?= e(num($b['quantity'])) ?><small><?= e(t('တင်း')) ?></small></strong></div><?php endforeach; ?><?php if(!$balances): ?><div class="empty"><?= e(t('No warehouses yet.')) ?></div><?php endif; ?>
<div class="panel-foot"><?= e(t('Balances update after every stock operation.')) ?></div></section></div>
<section class="panel"><div class="panel-heading"><div><div class="eyebrow"><?= e(t('STOCK LEDGER')) ?></div><h2><?= e(t('Recent activity')) ?></h2></div><a href="<?= e(url('stock-movements')) ?>"><?= e(t('View ledger →')) ?></a></div><?php require __DIR__.'/partials/movements.php'; ?></section>
