<section class="panel"><div class="panel-heading"><div><div class="eyebrow"><?= e(t('BUSINESS DIRECTORY')) ?></div><h2><?= e(t($definition['title'])) ?></h2></div><button class="button primary" type="button" data-open-record aria-haspopup="dialog" aria-controls="record-dialog"><?= e(t('＋ Add {type}',['type'=>t($definition['singular'])])) ?></button></div>
<?php if($pagination): require __DIR__.'/partials/list-filters.php'; else: ?><form class="filters" method="get" action="<?= e(url($type)) ?>"><label class="search-field"><?= e(t('Search')) ?> <?= e(t(strtolower($definition['title']))) ?><input type="search" name="q" value="<?= e($query) ?>" placeholder="<?= e(t('Search by name or details')) ?>"></label><button class="button" type="submit"><?= e(t('Search')) ?></button><a class="button" href="<?= e(url($type)) ?>"><?= e(t('Reset')) ?></a></form><?php endif; ?>
<div class="table-wrap"><table><thead><tr><th><?= e(t('Name')) ?></th><?php foreach($definition['fields'] as $field=>$limit): ?><th><?= e(t(ucfirst($field))) ?></th><?php endforeach; ?><?php if($type==='suppliers' && can('suppliers.credit')): ?><th class="number"><?= e(t('Balance to pay (MMK)')) ?></th><?php endif; ?><th class="table-actions"><?= e(t('Actions')) ?></th></tr></thead><tbody>
<?php foreach($rows as $row): ?><tr><td><strong><?= e($row['name']) ?></strong></td><?php foreach($definition['fields'] as $field=>$limit): ?><td class="notes-cell"><?= e($row[$field]?:'—') ?></td><?php endforeach; ?><?php if($type==='suppliers' && can('suppliers.credit')): ?><td class="number"><strong><?= e(money($row['balance'])) ?></strong></td><?php endif; ?><td class="table-actions"><div class="actions"><a class="button small" href="<?= e(url($type.'/'.$row['id'].'/edit')) ?>#record-form"><?= e(t('Edit')) ?></a><?php if($type==='suppliers' && can('suppliers.credit')): ?><a class="button small" href="<?= e(url('suppliers/'.$row['id'].'/credit')) ?>"><?= e(t('Credit / payments')) ?></a><?php endif; ?><form method="post" action="<?= e(url($type.'/'.$row['id'].'/delete')) ?>" data-confirm="<?= e(t('Delete ').$row['name'].t('? This cannot be undone. Records used in business history cannot be deleted.')) ?>"><?= csrf_field() ?><button class="button small danger" type="submit"><?= e(t('Delete')) ?></button></form></div></td></tr><?php endforeach; ?>
<?php if(!$rows): ?><tr><td colspan="<?= 2+count($definition['fields'])+($type==='suppliers' && can('suppliers.credit')?1:0) ?>" class="empty"><?= e(t('No {type} found.',['type'=>t(strtolower($definition['title']))])) ?></td></tr><?php endif; ?></tbody></table></div><?php if($pagination): require __DIR__.'/partials/pagination.php'; endif; ?><div class="panel-foot"><?= $pagination?$pagination->count:count($rows) ?> <?= e(t('records · Records used in stock or financial history are protected from deletion.')) ?></div></section>
<dialog id="record-dialog" class="record-dialog" aria-labelledby="record-dialog-title" data-auto-open="<?= $record || $formError?'true':'false' ?>" data-singular="<?= e($definition['singular']) ?>">
<div class="dialog-heading"><div><div class="eyebrow"><?= e(t('BUSINESS DIRECTORY')) ?></div><h2 id="record-dialog-title"><?= e(t($record?'Edit {type}':'Add {type}',['type'=>t($definition['singular'])])) ?></h2></div><button class="icon-button" type="button" data-close-record aria-label="<?= e(t('Close form')) ?>">×</button></div>
<?php if($formError): ?><div class="flash error dialog-error" role="alert"><?= e($formError) ?></div><?php endif; ?>
<form method="post" action="<?= e(url($type)) ?>" id="record-form"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($record['id']??0) ?>"><div class="form-grid"><?php field('name',t('Name'),'text',$record['name']??'','required maxlength="120" autofocus');foreach($definition['fields'] as $field=>$limit)field($field,ucfirst($field),$field==='phone'?'tel':'text',$record[$field]??'','maxlength="'.$limit.'"'); ?></div><div class="form-footer dialog-footer"><span class="muted" id="record-form-help"><?= $record?t('Changes apply to this directory record.'):e(t('Create a new {type} for your business.',['type'=>t($definition['singular'])])) ?></span><div class="actions"><button class="button" type="button" data-close-record><?= e(t('Cancel')) ?></button><button class="button primary" type="submit" id="record-submit"><?= $record?t('Save changes'):e(t('Create {type}',['type'=>t($definition['singular'])])) ?></button></div></div></form></dialog>
