<?php
$transfer=($kind??'production')==='transfer';
$operation=$transfer?'transfer':'production';
$ready=count($warehouses)>=($transfer?2:1) && $riceTypes;
$draft=old('items',[['rice_type_id'=>old('rice_type_id'),'quantity'=>old('quantity')]]);
if(!is_array($draft)||!$draft)$draft=[[]];
$renderItem=static function(array $item,int|string $index)use($riceTypes,$transfer):void { ?>
<tr class="purchase-item" data-index="<?= e($index) ?>"><td class="item-number"><?= is_int($index)?$index+1:'' ?></td>
<td><label><span class="sr-only"><?= e(t('Rice type')) ?></span><select name="items[<?= e($index) ?>][rice_type_id]" data-item-field="rice_type_id" data-searchable="true" required><option value=""><?= e(t('Select rice type')) ?></option><?php foreach($riceTypes as $rice): ?><option value="<?= e($rice['id']) ?>" <?= (string)($item['rice_type_id']??'')===(string)$rice['id']?'selected':'' ?>><?= e($rice['name']) ?></option><?php endforeach; ?></select></label></td>
<td><label><span class="sr-only"><?= $transfer?t('Quantity to transfer'):t('Quantity to production') ?> <?= e(t('(တင်း)')) ?></span><input type="number" name="items[<?= e($index) ?>][quantity]" data-item-field="quantity" value="<?= e($item['quantity']??'') ?>" min="0.001" max="999999999.999" step="0.001" required placeholder="0"></label></td>
<td class="number"><output class="item-available">—</output></td><td class="number"><output class="item-remaining">—</output></td><?php if($transfer): ?><td class="number"><output class="item-destination">&mdash;</output></td><?php endif; ?><td class="table-actions"><button class="button small remove-item" type="button" aria-label="<?= e(t('Remove rice item')) ?>" title="<?= e(t('Remove rice item')) ?>">×</button></td></tr>
<?php }; ?>
<?php if(!$ready): ?><div class="flash warning"><?= e(t($transfer?'Add at least two warehouses and a rice type before recording transfers.':'Add a warehouse and a rice type before recording production.')) ?> <?php if(can('settings.manage')): ?><a href="<?= e(url('warehouses')) ?>"><?= e(t('Open settings')) ?></a><?php endif; ?></div><?php endif; ?>
<form method="post" action="<?= e(url($formAction??$operation)) ?>" data-purchase-wizard data-operation="<?= e($operation) ?>" data-ready="<?= $ready?'true':'false' ?>" data-initial-step="<?= (int)old($operation.'_step',0) ?>" data-max-items="<?= \App\Services\Production::MAX_ITEMS ?>">
<?= csrf_field() ?><?php if(isset($editRecord)): ?><input type="hidden" name="version" value="<?= e(old('version',$editRecord['version'])) ?>"><?php endif; ?><input type="hidden" name="request_key" value="<?= e($requestKey) ?>">
<?php $wizardAria=t($transfer?'Stock transfer steps':'Production steps');$wizardLabels=[$transfer?t('Transfer details'):t('Production details'),t('Rice items'),t('Review & submit')];require __DIR__.'/partials/wizard-steps.php'; ?>
<div class="form-layout purchase-layout"><div>
<section class="panel purchase-step" data-step="0" aria-labelledby="purchase-step-0"><div class="panel-heading"><div><div class="eyebrow"><?= e(t('STEP 1 OF 3')) ?></div><h2 id="purchase-step-0" tabindex="-1"><?= $transfer?t('Transfer details'):t('Production details') ?></h2></div></div><p class="muted wizard-help"><?= $transfer?t('Choose the source and destination warehouses for all rice items.'):t('Choose the warehouse where rice will be used for production.') ?></p><div class="form-grid">
<?php field('occurred_on',$transfer?t('Transfer date'):t('Production date'),'date',date('Y-m-d'),'required');select_field('warehouse_id',t('Source warehouse'),$warehouses);if($transfer)select_field('destination_id',t('Destination warehouse'),$warehouses); ?>
<label class="full"><?= e(t('Notes')) ?> <span class="muted"><?= e(t('(optional)')) ?></span><textarea name="notes" rows="3" maxlength="4000" placeholder="<?= $transfer?t('Transfer reason or delivery notes'):t('Production batch or reason') ?>"><?= e(old('notes')) ?></textarea></label></div></section>
<section class="panel purchase-step" data-step="1" aria-labelledby="purchase-step-1"><div class="panel-heading"><div><div class="eyebrow"><?= e(t('STEP 2 OF 3')) ?></div><h2 id="purchase-step-1" tabindex="-1"><?= e(t('Rice items')) ?></h2></div><button class="button add-item" type="button" <?= !$ready?'disabled':'' ?>><?= e(t('+ Add rice item')) ?></button></div><p class="muted wizard-help"><?= e(t($transfer?'Enter the quantity to transfer for each rice type. Available and remaining stock are measured in တင်း.':'Enter the quantity used for each rice type. Available and remaining stock are measured in တင်း.')) ?></p>
<div class="table-wrap purchase-items-wrap"><table class="purchase-items-table production-items-table <?= $transfer?'transfer-items-table':'' ?>"><thead><tr><th scope="col"><?= e(t('No.')) ?></th><th scope="col"><?= e(t('Rice type')) ?></th><th scope="col" class="number"><?= e(t('Qty (တင်း)')) ?></th><th scope="col" class="number"><?= e(t('Available')) ?></th><th scope="col" class="number"><?= e(t('Source after')) ?></th><?php if($transfer): ?><th scope="col" class="number"><?= e(t('Dest. after')) ?></th><?php endif; ?><th scope="col" class="table-actions"><span class="sr-only"><?= e(t('Actions')) ?></span></th></tr></thead><tbody id="purchase-items"><?php foreach(array_values($draft) as $index=>$item)$renderItem(is_array($item)?$item:[],$index); ?></tbody></table></div><div class="panel-foot"><span id="item-count" role="status"><?= e(t('{count} rice item(s)',['count'=>count($draft)])) ?></span> <?= e(t('· Up to {max} items per {operation}',['max'=>\App\Services\Production::MAX_ITEMS,'operation'=>t(ucfirst($operation))])) ?></div><p class="muted grid-keyboard-help"><?= e(t('Tab: next cell · Enter / ↓: next row · Shift+Enter / ↑: previous row')) ?></p></section>
<section class="panel purchase-step" data-step="2" aria-labelledby="purchase-step-2"><div class="panel-heading"><div><div class="eyebrow"><?= e(t('STEP 3 OF 3')) ?></div><h2 id="purchase-step-2" tabindex="-1"><?= e(t($transfer?'Review transfer':'Review production')) ?></h2></div></div><div id="purchase-review" class="purchase-review"><div class="review-details"></div><div class="table-wrap"><table><thead><tr><th><?= e(t('Rice type')) ?></th><th class="number"><?= e(t('Available (တင်း)')) ?></th><th class="number"><?= $transfer?t('Transfer'):t('Used') ?> <?= e(t('(တင်း)')) ?></th><th class="number"><?= e(t('Source after (တင်း)')) ?></th><?php if($transfer): ?><th class="number"><?= e(t('Dest. before')) ?></th><th class="number"><?= e(t('Dest. after')) ?></th><?php endif; ?></tr></thead><tbody id="purchase-review-items"></tbody></table></div><p class="review-notes muted"></p></div><p class="muted wizard-help"><?= e(t('Confirm the rice quantities before submitting.')) ?> <?= $transfer?t('All items move between the selected warehouses together; total inventory stays the same.'):t('All items are deducted from the selected warehouse together.') ?></p></section>
<div class="panel form-footer wizard-footer"><a class="button" href="<?= e(url($cancelPath??(can('inventory.view')?'inventory':''))) ?>"><?= e(t('Cancel')) ?></a><div class="actions"><button class="button wizard-controls" type="button" id="purchase-back"><?= e(t('Back')) ?></button><button class="button primary wizard-controls" type="button" id="purchase-next" <?= !$ready?'disabled':'' ?>><?= e(t('Continue')) ?></button><button class="button primary" type="submit" id="purchase-save" <?= !$ready?'disabled':'' ?>><?= isset($editRecord)?t('Save changes'):($transfer?t('Transfer stock'):t('Submit production')) ?></button></div></div><div class="flash error" id="wizard-error" role="alert" hidden></div>
</div><aside class="panel summary-panel purchase-summary"><div class="eyebrow"><?= e(t($transfer?'Transfer summary':'Production summary')) ?></div><h2><?= $transfer?t('Move rice between warehouses'):t('Use rice for production') ?></h2><p class="muted" id="summary-destination"><?= e(t($transfer?'Choose source and destination warehouses.':'Choose a source warehouse.')) ?></p><div class="summary-line"><span><?= e(t('Rice items')) ?></span><strong id="wizard-item-count"><?= count($draft) ?></strong></div><div class="summary-total"><span><?= e(t($transfer?'Total quantity to transfer':'Total quantity used')) ?></span><strong id="wizard-quantity"><?= e(t('0 တင်း')) ?></strong></div><small class="muted"><?= e(t('Stock changes only after you submit. Availability is checked again when submitting.')) ?></small></aside></div>
<template id="purchase-item-template"><?php $renderItem([],'__INDEX__'); ?></template></form>
<script type="application/json" id="stock-balance-data"><?= json_encode($balances,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script>
<script src="<?= e(asset('js/purchase-wizard.js')) ?>" defer></script>
