<?php
$ready=$warehouses && $riceTypes && $suppliers;
$draft=old('items', [['rice_type_id'=>old('rice_type_id'),'quantity'=>old('quantity'),'unit_price'=>old('unit_price'),'weight_lb'=>old('weight_lb'),'price_lb'=>old('price_lb'),'quantity_bag'=>old('quantity_bag')]]);
if(!is_array($draft)||!$draft)$draft=[[]];
$renderItem=static function(array $item,int|string $index)use($riceTypes):void { ?>
<tr class="purchase-item" data-index="<?= e($index) ?>">
<td class="item-number"><?= is_int($index)?$index+1:'' ?></td>
<td><label><span class="sr-only"><?= e(t('Rice type')) ?></span><select name="items[<?= e($index) ?>][rice_type_id]" data-item-field="rice_type_id" data-searchable="true" required><option value=""><?= e(t('Select rice type')) ?></option><?php foreach($riceTypes as $rice): ?><option value="<?= e($rice['id']) ?>" <?= (string)($item['rice_type_id']??'')===(string)$rice['id']?'selected':'' ?>><?= e($rice['name']) ?></option><?php endforeach; ?></select></label></td>
<?php foreach(['quantity'=>[t('Quantity (တင်း)'),'0.001','999999999.999','0.001',true],'quantity_bag'=>[t('Qty (အိတ်)'),'0','999999999.999','0.001',false],'weight_lb'=>[t('Weight (ပေါင်)'),'0.001','999999999.999','0.001',false],'unit_price'=>[t('Price per တင်း (MMK)'),'0.01','999999999.99','0.01',true],'price_lb'=>[t('Price / lb'),'0','999999999.99','0.01',false]] as $field=>[$label,$min,$max,$step,$required]): ?>
<td><label><span class="sr-only"><?= e(t($label)) ?></span><input type="number" name="items[<?= e($index) ?>][<?= e($field) ?>]" data-item-field="<?= e($field) ?>" value="<?= e($item[$field]??'') ?>" min="<?= $min ?>" max="<?= $max ?>" step="<?= $step ?>" <?= $required?'required':'' ?> placeholder="<?= in_array($field,['weight_lb','quantity_bag'],true)?t('Optional'):'0' ?>"></label></td>
<?php endforeach; ?>
<td class="number"><output class="item-amount">0.00</output></td><td class="table-actions"><button class="button small remove-item" type="button" aria-label="<?= e(t('Remove rice item')) ?>" title="<?= e(t('Remove rice item')) ?>">×</button></td></tr>
<?php }; ?>
<?php if(!$ready): ?><div class="flash warning"><?= e(t('Add a warehouse, rice type and supplier before recording a purchase.')) ?> <?php if(can('settings.manage')): ?><a href="<?= e(url('warehouses')) ?>"><?= e(t('Open settings')) ?></a><?php endif; ?></div><?php endif; ?>
<form method="post" action="<?= e(url($formAction??'purchase/new')) ?>" data-purchase-wizard data-ready="<?= $ready?'true':'false' ?>" data-initial-step="<?= (int)old('purchase_step',0) ?>" data-max-items="<?= \App\Services\Purchase::MAX_ITEMS ?>">
<?= csrf_field() ?><?php if(isset($editRecord)): ?><input type="hidden" name="version" value="<?= e(old('version',$editRecord['version'])) ?>"><?php endif; ?><input type="hidden" name="request_key" value="<?= e($requestKey) ?>">
<?php $wizardAria=t('Purchase steps');$wizardLabels=[t('Purchase details'),t('Rice items'),t('Payment & review')];require __DIR__.'/partials/wizard-steps.php'; ?>
<div class="form-layout purchase-layout"><div>
<section class="panel purchase-step" data-step="0" aria-labelledby="purchase-step-0"><div class="panel-heading"><div><div class="eyebrow"><?= e(t('STEP 1 OF 3')) ?></div><h2 id="purchase-step-0" tabindex="-1"><?= e(t('Purchase details')) ?></h2></div></div><p class="muted wizard-help"><?= e(t('Choose who you are buying from and where all rice items will be received.')) ?></p><div class="form-grid">
<?php field('occurred_on',t('Purchase date'),'date',date('Y-m-d'),'required');select_field('warehouse_id',t('Receiving warehouse'),$warehouses);select_field('supplier_id',t('Supplier'),$suppliers); ?>
<label class="full"><?= e(t('Notes')) ?> <span class="muted"><?= e(t('(optional)')) ?></span><textarea name="notes" rows="3" maxlength="4000" placeholder="<?= e(t('Delivery details or purchase notes')) ?>"><?= e(old('notes')) ?></textarea></label></div></section>
<section class="panel purchase-step" data-step="1" aria-labelledby="purchase-step-1"><div class="panel-heading"><div><div class="eyebrow"><?= e(t('STEP 2 OF 3')) ?></div><h2 id="purchase-step-1" tabindex="-1"><?= e(t('Rice items')) ?></h2></div><button class="button add-item" type="button" <?= !$ready?'disabled':'' ?>><?= e(t('+ Add rice item')) ?></button></div><p class="muted wizard-help"><?= e(t('Amount = quantity (tin) × price/tin + weight (lb) × price/lb. Bag quantity is recorded per item.')) ?></p>
<div class="table-wrap purchase-items-wrap"><table class="purchase-items-table purchase-pricing-table"><thead><tr><th scope="col"><?= e(t('No.')) ?></th><th scope="col"><?= e(t('Rice type')) ?></th><th scope="col" class="number" aria-label="<?= e(t('Quantity (တင်း)')) ?>"><?= e(t('Qty (တင်း)')) ?></th><th scope="col" class="number"><?= e(t('Qty (အိတ်)')) ?></th><th scope="col" class="number"><?= e(t('Weight (ပေါင်)')) ?></th><th scope="col" class="number"><?= e(t('Price / တင်း')) ?></th><th scope="col" class="number"><?= e(t('Price / lb')) ?></th><th scope="col" class="number"><?= e(t('Amount')) ?></th><th scope="col" class="table-actions"><span class="sr-only"><?= e(t('Actions')) ?></span></th></tr></thead><tbody id="purchase-items"><?php foreach(array_values($draft) as $index=>$item)$renderItem(is_array($item)?$item:[],$index); ?></tbody></table></div><div class="panel-foot"><span id="item-count" role="status"><?= e(t('{count} rice item(s)',['count'=>count($draft)])) ?></span> <?= e(t('· Prices and amounts in MMK · Up to {max} items per purchase',['max'=>\App\Services\Purchase::MAX_ITEMS])) ?></div><p class="muted grid-keyboard-help"><?= e(t('Tab: next cell · Enter / ↓: next row · Shift+Enter / ↑: previous row')) ?></p></section>
<section class="panel purchase-step" data-step="2" aria-labelledby="purchase-step-2"><div class="panel-heading"><div><div class="eyebrow"><?= e(t('STEP 3 OF 3')) ?></div><h2 id="purchase-step-2" tabindex="-1"><?= e(t('Payment & review')) ?></h2></div></div>
<div id="purchase-review" class="purchase-review"><div class="review-details"></div><div class="table-wrap"><table><thead><tr><th><?= e(t('Rice type')) ?></th><th class="number"><?= e(t('Quantity (တင်း)')) ?></th><th class="number"><?= e(t('Qty (အိတ်)')) ?></th><th class="number"><?= e(t('Weight (ပေါင်)')) ?></th><th class="number"><?= e(t('Price / တင်း')) ?></th><th class="number"><?= e(t('Price / lb')) ?></th><th class="number"><?= e(t('Amount (MMK)')) ?></th></tr></thead><tbody id="purchase-review-items"></tbody></table></div></div>
<div class="form-grid"><?php field('amount_paid',t('Paid now (MMK)'),'number','0','required min="0" step="0.01"'); ?><div class="payment-help"><p class="muted"><?= e(t('Enter 0 for credit, a partial payment, or pay the full total.')) ?></p><button class="button small" type="button" id="wizard-pay-full"><?= e(t('Set fully paid')) ?></button></div></div><p class="muted wizard-help"><?= e(t('Saving creates one voucher, receives all rice items into your warehouse, and records the unpaid total as supplier credit.')) ?></p></section>
<div class="panel form-footer wizard-footer"><a class="button" href="<?= e(url($cancelPath??(can('inventory.view')?'inventory':''))) ?>"><?= e(t('Cancel')) ?></a><div class="actions"><button class="button wizard-controls" type="button" id="purchase-back"><?= e(t('Back')) ?></button><button class="button primary wizard-controls" type="button" id="purchase-next" <?= !$ready?'disabled':'' ?>><?= e(t('Continue')) ?></button><button class="button primary" type="submit" id="purchase-save" <?= !$ready?'disabled':'' ?>><?= isset($editRecord)?t('Save changes'):t('Save purchase') ?></button></div></div>
<div class="flash error" id="wizard-error" role="alert" hidden></div>
</div><aside class="panel summary-panel purchase-summary"><div class="eyebrow"><?= e(t('PURCHASE SUMMARY')) ?></div><h2><?= e(t('Receive rice')) ?></h2><p class="muted" id="summary-destination"><?= e(t('Choose a supplier and receiving warehouse.')) ?></p><div class="summary-line"><span><?= e(t('Rice items')) ?></span><strong id="wizard-item-count"><?= count($draft) ?></strong></div><div class="summary-line"><span><?= e(t('Total quantity')) ?></span><strong id="wizard-quantity"><?= e(t('0 တင်း')) ?></strong></div><div class="summary-total"><span><?= e(t('Purchase amount')) ?></span><strong id="wizard-amount"><?= e(t('0.00 MMK')) ?></strong></div><div class="summary-line"><span><?= e(t('Paid now')) ?></span><strong id="wizard-paid"><?= e(t('0.00 MMK')) ?></strong></div><div class="summary-line"><span><?= e(t('Supplier credit')) ?></span><strong id="wizard-credit"><?= e(t('0.00 MMK')) ?></strong></div><small class="muted"><?= e(t('Stock changes only after you save the purchase.')) ?></small></aside></div>
<template id="purchase-item-template"><?php $renderItem([],'__INDEX__'); ?></template>
</form>
<script src="<?= e(asset('js/purchase-wizard.js')) ?>" defer></script>
