<?php $ready=count($warehouses)>=($kind==='transfer'?2:1) && $riceTypes && ($kind!=='purchase' || $suppliers); ?>
<?php if(!$ready): ?><div class="flash warning"><?= e(t('Before continuing, add')) ?> <?= $kind==='transfer'?t('at least two warehouses and a rice type'):($kind==='purchase'?t('a warehouse, rice type and supplier'):t('a warehouse and rice type')) ?> <?= e(t('in business settings.')) ?> <?php if(can('settings.manage')): ?><a href="<?= e(url('settings')) ?>"><?= e(t('Open settings →')) ?></a><?php endif; ?></div><?php endif; ?>
<div class="form-layout"><section class="panel"><div class="panel-heading"><h2><?= e(t('{title} details',['title'=>t($title)])) ?></h2><span class="badge <?= e($kind) ?>"><?= e(t(ucfirst($kind))) ?></span></div><form method="post" class="stock-form" data-kind="<?= e($kind) ?>">
<?= csrf_field() ?><input type="hidden" name="request_key" value="<?= e($requestKey) ?>">
<div class="form-grid"><?php field('occurred_on',$kind==='purchase'?t('Purchase date'):t('Operation date'),'date',date('Y-m-d'),'required'); select_field('warehouse_id',$kind==='transfer'?t('From warehouse'):t('Warehouse'),$warehouses); ?>
<?php if($kind==='purchase') select_field('supplier_id',t('Supplier'),$suppliers); if($kind==='transfer') select_field('destination_id',t('To warehouse'),$warehouses); select_field('rice_type_id',t('Rice type'),$riceTypes); field('quantity',t('Quantity (တင်း)'),'number','','required min="0.001" max="999999999.999" step="0.001"'); if($kind==='purchase') field('unit_price',t('Price per တင်း (MMK)'),'number','','required min="0.01" max="999999999.99" step="0.01"'); ?>
<?php if($kind==='purchase'): ?><?php field('weight_lb',t('Weight (ပေါင်) — optional'),'number','','min="0.001" max="999999999.999" step="0.001"'); field('amount_paid',t('Paid now (MMK)'),'number','0','required min="0" step="0.01"'); ?><div class="payment-help full"><p class="muted"><?= e(t('Enter 0 for a credit purchase, a partial payment, or the full purchase amount.')) ?></p><button type="button" class="button small" id="pay-in-full"><?= e(t('Set fully paid')) ?></button></div><?php endif; ?>
<label class="full"><?= e(t('Notes')) ?> <span class="muted"><?= e(t('(optional)')) ?></span><textarea name="notes" rows="3" maxlength="4000" placeholder="<?= e(t('Delivery details, transfer reason or production batch')) ?>"><?= e(old('notes')) ?></textarea></label></div>
<div class="form-footer"><span class="muted"><?= e(t('Stock updates when you submit.')) ?></span><div class="actions"><a class="button" href="<?= e(url(can('inventory.view')?'inventory':'')) ?>"><?= e(t('Cancel')) ?></a><button class="button primary" type="submit" <?= !$ready?'disabled':'' ?>><?= ['purchase'=>t('Save purchase'),'transfer'=>t('Transfer stock'),'production'=>t('Submit production')][$kind] ?> →</button></div></div></form></section>
<aside class="panel summary-panel"><div class="eyebrow"><?= e(t('OPERATION SUMMARY')) ?></div><h2><?= $kind==='purchase'?t('Receive rice'):($kind==='transfer'?t('Move rice'):t('Use rice for production')) ?></h2><p><?= ['purchase'=>t('The quantity will be added to your selected warehouse. A purchase voucher will be created.'),'transfer'=>t('The source balance decreases and the destination balance increases by the same quantity.'),'production'=>t('The quantity will be deducted from your selected warehouse.')][$kind] ?></p><div class="summary-line"><span><?= $kind==='purchase'?t('Quantity received'):t('Quantity used / moved') ?></span><strong id="quantity-preview"><?= e(t('0 တင်း')) ?></strong></div><?php if($kind==='purchase'): ?><div class="summary-total"><span><?= e(t('Purchase amount')) ?></span><strong id="amount-preview">0.00 <small><?= e(t('MMK')) ?></small></strong></div><?php else: ?><div class="summary-total"><span><?= e(t('Available in source')) ?></span><strong id="balance-preview"><?= e(t('Select warehouse & rice type')) ?></strong></div><small class="muted"><?= e(t('Availability is checked again when submitting.')) ?></small><?php endif; ?></aside></div>
<script type="application/json" id="balance-data"><?= json_encode($balances,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script>
<?php if($kind==='purchase'): ?><div class="panel"><div class="summary-line"><span><?= e(t('Supplier credit from this purchase')) ?></span><strong id="credit-preview"><?= e(t('0.00 MMK')) ?></strong></div><p class="muted"><?= e(t('Any unpaid amount is added to the supplier balance to be paid.')) ?></p></div><?php endif; ?>
