<?php
$settings=\App\Services\VoucherSettings::get();
$paper=isset(\App\Services\VoucherSettings::PAPERS[$settings['paper_size']])?$settings['paper_size']:'A4';
$receipt=!in_array($paper,['A4','A5'],true);
$width=$receipt?(int)$paper:($paper==='A5'?148:210);
$preview=$preview??false;
$items=$items??[$p];
$showWeight=$settings['show_weight'] || array_filter($items,static fn($item)=>(float)($item['price_lb']??0)>0);
?>
<style id="voucher-paper-style">@page { size: <?= $receipt?$width.'mm 300mm':$paper.' portrait' ?>; margin: <?= $receipt?'3mm':($paper==='A5'?'10mm':'12mm') ?>; }</style>
<div class="actions voucher-actions"><a class="button" href="<?= e(url($preview?'voucher-settings':'purchases')) ?>"><?= $preview?t('← Voucher settings'):t('← Purchase register') ?></a><?php if(!$preview && can('settings.manage')): ?><a class="button" href="<?= e(url('voucher-settings')) ?>"><?= e(t('Voucher settings')) ?></a><?php endif; ?><?php if(!$preview): ?><a class="button" href="<?= e(url('purchase/'.$p['id'])) ?>"><?= e(t('Purchase details')) ?></a><?php endif; ?><span class="muted"><?= e(t(\App\Services\VoucherSettings::PAPERS[$paper])) ?></span><button class="button primary" id="print-voucher"><?= e(t('Print voucher')) ?></button></div>
<?php if($preview): ?><div class="flash"><?= e(t('Preview with sample data and your saved settings. No business records are created.')) ?></div><?php endif; ?>
<article class="voucher panel" data-paper="<?= e($paper) ?>" data-receipt="<?= $receipt?'true':'false' ?>" style="--voucher-paper-width:<?= $width ?>mm">
<div class="voucher-header"><div class="voucher-business"><?php if($logoUrl=\App\Services\VoucherSettings::logoUrl($settings)): ?><img class="voucher-company-logo" src="<?= e($logoUrl) ?>" alt="<?= e($settings['business_name']) ?> logo"><?php endif; ?><h2 class="voucher-business-name"><?= e($settings['business_name']) ?></h2><?php if($settings['header_text']!==''): ?><p class="voucher-header-text"><?= nl2br(e($settings['header_text'])) ?></p><?php endif; ?><?php if($settings['address']!==''): ?><p><?= nl2br(e($settings['address'])) ?></p><?php endif; ?><?php foreach(['phone','email','website'] as $field): if($settings[$field]!==''): ?><p><?= e($settings[$field]) ?></p><?php endif; endforeach; ?><?php if($settings['registration_no']!==''): ?><p><?= e(t('Registration:')) ?> <?= e($settings['registration_no']) ?></p><?php endif; ?></div><div class="number voucher-reference"><h2><?= e($settings['voucher_title']) ?></h2><strong><?= e($p['reference']) ?></strong><small><?= e($p['purchased_on']) ?></small></div></div>
<div class="voucher-details"><div><span class="eyebrow"><?= e(t('PURCHASED FROM')) ?></span><h2><?= e($p['supplier']) ?></h2><p><?= e($p['phone']) ?><br><?= e($p['address']) ?></p></div><div><span class="eyebrow"><?= e(t('RECEIVED AT')) ?></span><h2><?= e($p['warehouse']) ?></h2><p><?= e($p['location']) ?></p></div></div>
<?php if($receipt): ?><?php foreach($items as $item): ?><div class="receipt-item"><strong><?= e($item['rice']) ?></strong><div class="receipt-row"><span><?= e(t('Quantity (တင်း)')) ?></span><strong><?= e(num($item['quantity'])) ?></strong></div><?php if($settings['show_weight'] || (float)($item['price_lb']??0)>0): ?><div class="receipt-row"><span><?= e(t('Weight (ပေါင်)')) ?></span><strong><?= $item['weight_lb']!==null?e(num($item['weight_lb'])):'—' ?></strong></div><?php endif; ?><div class="receipt-row"><span><?= e(t('Qty (အိတ်)')) ?></span><strong><?= isset($item['quantity_bag'])?e(num($item['quantity_bag'])):'—' ?></strong></div><div class="receipt-row"><span><?= e(t('MMK / တင်း')) ?></span><strong><?= e(money($item['unit_price'])) ?></strong></div><div class="receipt-row"><span><?= e(t('Price / lb')) ?></span><strong><?= e(money($item['price_lb']??0)) ?></strong></div><div class="receipt-row"><span><?= e(t('Amount (MMK)')) ?></span><strong><?= e(money($item['amount'])) ?></strong></div></div><?php endforeach; ?>
<?php else: ?><div class="table-wrap"><table><thead><tr><th><?= e(t('Rice type')) ?></th><th class="number"><?= e(t('Quantity (တင်း)')) ?></th><th class="number"><?= e(t('Qty (အိတ်)')) ?></th><?php if($showWeight): ?><th class="number"><?= e(t('Weight (ပေါင်)')) ?></th><?php endif; ?><th class="number"><?= e(t('Price / တင်း')) ?></th><th class="number"><?= e(t('Price / lb')) ?></th><th class="number"><?= e(t('Amount (MMK)')) ?></th></tr></thead><tbody><?php foreach($items as $item): ?><tr><td><strong><?= e($item['rice']) ?></strong></td><td class="number"><?= e(num($item['quantity'])) ?></td><td class="number"><?= isset($item['quantity_bag'])?e(num($item['quantity_bag'])):'—' ?></td><?php if($showWeight): ?><td class="number"><?= $item['weight_lb']!==null?e(num($item['weight_lb'])):'—' ?></td><?php endif; ?><td class="number"><?= e(money($item['unit_price'])) ?></td><td class="number"><?= e(money($item['price_lb']??0)) ?></td><td class="number"><?= e(money($item['amount'])) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
<div class="voucher-total"><span><?= e(t('Total purchase amount')) ?></span><strong><?= e(money($p['amount'])) ?> <?= e(t('MMK')) ?></strong></div>
<div class="voucher-payment"><span><?= e(t('Paid at purchase:')) ?> <strong><?= e(money($p['amount_paid'])) ?> <?= e(t('MMK')) ?></strong></span><span><?= e(t('Credit at purchase:')) ?> <strong><?= e(money((float)$p['amount']-(float)$p['amount_paid'])) ?> <?= e(t('MMK')) ?></strong></span></div>
<?php if($p['notes']): ?><p class="voucher-notes"><strong><?= e(t('Notes')) ?></strong><br><?= nl2br(e($p['notes'])) ?></p><?php endif; ?>
<?php if($settings['show_recorded_by']): ?><p class="muted"><?= e(t('Recorded by')) ?> <?= e($p['recorded_by']) ?> · <?= e($p['created_at']) ?></p><?php endif; ?>
<?php if($settings['show_signatures']): ?><div class="signatures"><span><?= e(t('Supplier signature')) ?></span><span><?= e(t('Received by')) ?></span><span><?= e(t('Authorized by')) ?></span></div><?php endif; ?>
<div class="panel-foot"><?= e(t('Stock received:')) ?> <?= e(num($p['quantity'])) ?> <?= e(t('တင်း ·')) ?> <?= e($p['warehouse']) ?></div>
<?php if($settings['footer_text']!==''): ?><div class="voucher-custom-footer"><?= nl2br(e($settings['footer_text'])) ?></div><?php endif; ?>
</article>
