<form method="post" enctype="multipart/form-data" action="<?= e(url('voucher-settings')) ?>"><?= csrf_field() ?>
<div class="form-layout"><section class="panel"><div class="panel-heading"><div><div class="eyebrow"><?= e(t('VOUCHER CONTENT')) ?></div><h2><?= e(t('Business details & printed text')) ?></h2></div></div><div class="form-grid">
<?php field('business_name',t('Company name'),'text',$settings['business_name'],'required maxlength="120"');field('voucher_title',t('Voucher title'),'text',$settings['voucher_title'],'required maxlength="120"'); ?>
<div class="full company-logo-setting">
<?php if($logoUrl=\App\Services\VoucherSettings::logoUrl($settings)): ?><img class="company-logo-preview" src="<?= e($logoUrl) ?>" alt="<?= e(t('Current company logo')) ?>"><?php endif; ?>
<label><?= e(t('Company logo')) ?><input type="file" name="company_logo" accept="image/png,image/jpeg,image/webp" aria-describedby="logo-help"></label>
<small class="muted" id="logo-help"><?= e(t('PNG, JPG or WebP, up to 2 MB and 4096 × 4096 pixels. Shown in the app and on all purchase vouchers.')) ?></small>
<?php if($logoUrl): ?><label class="check"><input type="checkbox" name="remove_logo" value="1"><?= e(t('Remove current logo')) ?></label><?php endif; ?>
</div>
<label class="full"><?= e(t('Header text')) ?><textarea name="header_text" rows="3" maxlength="2000"><?= e(old('header_text',$settings['header_text'])) ?></textarea></label>
<label class="full"><?= e(t('Business address')) ?><textarea name="address" rows="3" maxlength="1000"><?= e(old('address',$settings['address'])) ?></textarea></label>
<?php field('phone',t('Phone / contact numbers'),'text',$settings['phone'],'maxlength="80"');field('email',t('Email'),'text',$settings['email'],'maxlength="190"');field('website',t('Website'),'text',$settings['website'],'maxlength="255"');field('registration_no',t('Business / tax registration number'),'text',$settings['registration_no'],'maxlength="120"'); ?>
<label class="full"><?= e(t('Footer text')) ?><textarea name="footer_text" rows="3" maxlength="2000" placeholder="<?= e(t('Thank you message, terms or other voucher information')) ?>"><?= e(old('footer_text',$settings['footer_text'])) ?></textarea></label></div></section>
<aside class="panel summary-panel"><div class="eyebrow"><?= e(t('PRINT LAYOUT')) ?></div><h2><?= e(t('Paper & information')) ?></h2><label><?= e(t('Default paper size')) ?><select name="paper_size" required><?php foreach($papers as $value=>$label): ?><option value="<?= e($value) ?>" <?= old('paper_size',$settings['paper_size'])===$value?'selected':'' ?>><?= e(t($label)) ?></option><?php endforeach; ?></select></label><p><?= e(t('A4 and A5 use a document layout. Receipt sizes use a compact layout that fits the selected width.')) ?></p>
<?php foreach(['show_weight'=>t('Show weight (ပေါင်)'),'show_signatures'=>t('Show signature lines'),'show_recorded_by'=>t('Show recorded by and timestamp')] as $key=>$label): ?><label class="check"><input type="checkbox" name="<?= e($key) ?>" value="1" <?= old($key,$settings[$key])?'checked':'' ?>><?= e(t($label)) ?></label><?php endforeach; ?>
<p><?= e(t('Save your changes, then open the preview to check the voucher.')) ?></p><a class="button" href="<?= e(url('voucher-settings/preview')) ?>"><?= e(t('Preview saved voucher')) ?></a><p class="muted"><?= e(t('In the print dialog, select matching printer paper and disable browser headers and footers.')) ?></p></aside></div>
<div class="panel form-footer"><span class="muted"><?= e(t('Company name and logo update the app branding and purchase vouchers.')) ?></span><button class="button primary" type="submit"><?= e(t('Save voucher settings')) ?></button></div></form>
